name:                 counterpoint-lh
version:              0.1.0.0
visibility:           public
id:                   counterpoint-lh-0.1.0.0-inplace
key:                  counterpoint-lh-0.1.0.0-inplace
license:              BSD-3-Clause
synopsis:
    Two-voice counterpoint verified by LiquidHaskell refinement types

description:
    Compile-time verification of species counterpoint rules
    (e.g. no parallel fifths/octaves) using LiquidHaskell and Z3.

abi:                  inplace
exposed:              True
exposed-modules:      Counterpoint Examples
import-dirs:
    /Users/sakano/univ/lab/project/counterpoint-lh/dist-newstyle/build/aarch64-osx/ghc-9.12.2/counterpoint-lh-0.1.0.0/build

library-dirs:
    /Users/sakano/univ/lab/project/counterpoint-lh/dist-newstyle/build/aarch64-osx/ghc-9.12.2/counterpoint-lh-0.1.0.0/build

library-dirs-static:
    /Users/sakano/univ/lab/project/counterpoint-lh/dist-newstyle/build/aarch64-osx/ghc-9.12.2/counterpoint-lh-0.1.0.0/build

dynamic-library-dirs:
    /Users/sakano/univ/lab/project/counterpoint-lh/dist-newstyle/build/aarch64-osx/ghc-9.12.2/counterpoint-lh-0.1.0.0/build

data-dir:             /Users/sakano/univ/lab/project/counterpoint-lh/.
hs-libraries:         HScounterpoint-lh-0.1.0.0-inplace
depends:
    base-4.21.0.0-958c lqdhskll-0.9.12.2.1-0bedea31
    process-1.6.25.0-f9e0

haddock-interfaces:
    /Users/sakano/univ/lab/project/counterpoint-lh/dist-newstyle/build/aarch64-osx/ghc-9.12.2/counterpoint-lh-0.1.0.0/doc/html/counterpoint-lh/counterpoint-lh.haddock

haddock-html:
    /Users/sakano/univ/lab/project/counterpoint-lh/dist-newstyle/build/aarch64-osx/ghc-9.12.2/counterpoint-lh-0.1.0.0/doc/html/counterpoint-lh
